[sailfish-webview] Make PermissionModel::setPermissionList to handle insert and remove. Fixes JB#52375
sailfishos/sailfish-components-webview pull request #87
Opened 2020-12-14 09:42 UTC by atatarov

2020-12-15 10:40 UTC, rainemak requested changes
Not like this.

You should compare permission list parameter and current status of the m_permissionList and do row removes and inserts accordingly.

2021-05-04 11:38 UTC, atatarov commented
testing needed

2021-06-10 16:05 UTC, llewelld reviewed
The code for updating the model looks sensible to me. I didn't notice any issues when testing it either.

Nice changes. I've made just one suggestion.

2021-06-11 09:08 UTC, atatarov commented on import/controls/permissionmodel.cpp
> +        emit dataChanged(index(startIndex), index(m_permissionList.count()-1));
Thank you, done

2021-06-11 10:12 UTC, llewelld approved these changes
This looks good to me, and also seemed to work fine during brief testing.

2021-06-11 19:23 UTC, okodron approved these changes

2021-06-14 05:47 UTC, rainemak approved these changes
@llewelld already approved. Approving as well.

2021-06-14 05:48 UTC, merged